name: dartgun
description: A Dart port for gunjs.
version: 0.1.0
repository: https://github.com/abhimanyupandian/dartgun

environment:
  sdk: '>=2.14.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  web_socket_channel: ^2.1.0
